import 'styles/globals.css';

import { CookiesProvider } from '@/provider/CookiesProvider';
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import { ModalProvider } from '@/provider/ModalProvider';
import { QueryProvider } from 'src/provider/QueryProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <QueryProvider>
                    <CookiesProvider>
                        <ModalProvider />
                        {children}
                    </CookiesProvider>
                </QueryProvider>
            </body>
        </html>
    );
}
